version: '3.3'
services:

  ecommerce-mysql:
    image: mysql:5.7
    networks:
      - ecommerce-net
    restart: always
    environment:
      MYSQL_DATABASE: 'ecommerce'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3308:3306'

    volumes:
      - my-db:/var/lib/mysql


  adminer:
    image: adminer
    restart: always
    ports:
      - 8182:8080
    networks:
      - ecommerce-net

  ecommerce-main:
    image: juanqui89/ecommercefactorit
    ports:
      - 8087:8087
    environment:
      DATABASE_HOST: 'ecommerce-mysql'
      DATABASE_PORT: '3038'
      DATABASE_NAME: 'ecommerce'
      DATABASE_USER: 'user'
      DATABASE_PASSWORD: 'password'

      SPRING_DATASOURCE_URL: 'jdbc:mysql://ecommerce-mysql:3306/ecommerce?autoReconnect=true&useSSL=false'

    depends_on:
      - ecommerce-mysql
    networks:
      - ecommerce-net
volumes:
  my-db:

networks:
  ecommerce-net: