server:
  port: 8087

spring:
  profiles:
    active: dev
  output:
    ansi:
      enabled: always

---
spring:
  profiles: dev
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: password
    url: jdbc:mysql://localhost:3308/ecommerce
    username: user
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#    defer-datasource-initialization: true